Doit: allow private editions

diff --git a/Doit b/Doit
--- a/Doit
+++ b/Doit
@@ -31,6 +31,9 @@ do
 		continue
 	}
 
+	private=$(git rev-parse -q --verify private-$branch 2>/dev/null)
+	case $? in 0|1) ;; *) exit $? ;; esac
+
 	if	installed=$($HOME/git-$branch/bin/git version) &&
 		if version=$(expr "$installed" : '.*\.g\([0-9a-f]*\)$')
 		then
@@ -52,6 +55,18 @@ do
 
 	echo "** $branch" &&
 	git checkout $branch &&
+
+	case "$private" in
+	'')
+		;;
+	?*)
+		git merge --squash --no-commit "$private" || {
+			echo >&2 "Cannot apply private edition changes"
+			git reset --hard
+		}
+		;;
+	esac &&
+
 	Meta/Make $M -- $J clean &&
 	case "$with_dash" in
 	y)
@@ -63,6 +78,7 @@ do
 		esac
 		;;
 	esac &&
+
 	Meta/Make $M -- $J all &&
 	Meta/Make $M -- $J test &&
 	case "$branch" in
@@ -77,6 +93,8 @@ do
 	esac &&
 	Meta/Make $M -- install &&
 	Meta/Make clean || exit $?
+
+	git reset --hard
 
 done >./:all.log 3>&2 2>&1
 
