When the patch tries to create a new file and the file exists, abort.
This fixes an error introduced to git-apply-patch-script in the previous
round.  We do not invoke patch for create/delete case, so we need to
be a bit careful about detecting conflicts like this.

Signed-off-by: Junio C Hamano <junkio@cox.net>

diff --git a/git-apply-patch-script b/git-apply-patch-script
--- a/git-apply-patch-script
+++ b/git-apply-patch-script
@@ -28,6 +28,15 @@ case "$mode1,$mode2" in
 	echo >&2 "cannot create leading path for $name."
 	exit 1
     }
+    if test -f "$name"
+    then
+	echo >&2 "file $name to be created already exists."
+	exit 1
+    fi
+    cat "$tmp2" >"$name" || {
+	echo >&2 "cannot create $name."
+	exit 1
+    } 
     case "$mode2" in
     +x)
 	echo >&2 "created $name with mode +x."
